# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googletrack',
            name='user',
        ),
        migrations.RemoveField(
            model_name='spotifytrack',
            name='user',
        ),
    ]
