# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170221_0049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tracklink',
            options={'ordering': ['order']},
        ),
    ]
