# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 02:10
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170221_0126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['tracklink__order']},
        ),
        migrations.AddField(
            model_name='googletrack',
            name='google_id',
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='googletrack',
            name='nid',
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='googletrack',
            name='track',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Track'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='googletrack',
            name='track_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
