# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170221_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='album',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='album_image',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
