# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170226_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='googletrack',
            name='service',
            field=models.CharField(choices=[('sp', 'Spotify'), ('gm', 'Google Music'), ('yt', 'YouTube')], default='gm', max_length=2),
        ),
        migrations.AddField(
            model_name='spotifytrack',
            name='service',
            field=models.CharField(choices=[('sp', 'Spotify'), ('gm', 'Google Music'), ('yt', 'YouTube')], default='sp', max_length=2),
        ),
    ]
