# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 05:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_auto_20170221_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='googletrack',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spotifytrack',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tracklink',
            name='status',
            field=models.CharField(default='live', max_length=255),
            preserve_default=False,
        ),
    ]
