# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170226_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='link',
        ),
        migrations.RemoveField(
            model_name='playlistlink',
            name='source',
        ),
        migrations.AddField(
            model_name='playlistlink',
            name='sources',
            field=models.ManyToManyField(to='app.Playlist'),
        ),
        migrations.AlterField(
            model_name='googletrack',
            name='service',
            field=models.CharField(choices=[('sp', 'Spotify'), ('gm', 'Google Music')], default='gm', max_length=2),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='service',
            field=models.CharField(choices=[('sp', 'Spotify'), ('gm', 'Google Music')], max_length=2),
        ),
        migrations.AlterField(
            model_name='playlistlink',
            name='destination',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='destination_playlist_id', to='app.Playlist'),
        ),
        migrations.AlterField(
            model_name='spotifytrack',
            name='service',
            field=models.CharField(choices=[('sp', 'Spotify'), ('gm', 'Google Music')], default='sp', max_length=2),
        ),
    ]
