# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170227_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracklink',
            name='entry_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
