# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_tracklink_entry_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='googletrack',
            name='google_track_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='googletrack',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='googletrack',
            name='nid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
