# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170303_0537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googletrack',
            name='google_track_id',
        ),
        migrations.AlterField(
            model_name='googletrack',
            name='google_id',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='googletrack',
            name='nid',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
