# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_youtubeprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtubeprofile',
            old_name='credential',
            new_name='credentials',
        ),
    ]
