# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_youtubeplaylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googletrack',
            name='service',
            field=models.CharField(choices=[('sp', 'Spotify'), ('gm', 'Google Music'), ('yt', 'YouTube')], default='gm', max_length=2),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='service',
            field=models.CharField(choices=[('sp', 'Spotify'), ('gm', 'Google Music'), ('yt', 'YouTube')], max_length=2),
        ),
        migrations.AlterField(
            model_name='spotifytrack',
            name='service',
            field=models.CharField(choices=[('sp', 'Spotify'), ('gm', 'Google Music'), ('yt', 'YouTube')], default='sp', max_length=2),
        ),
    ]
