# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 20:24
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0014_auto_20170304_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('service', models.CharField(choices=[('sp', 'Spotify'), ('gm', 'Google Music'), ('yt', 'YouTube')], default='yt', max_length=2)),
                ('youtube_id', models.CharField(max_length=255, unique=True)),
                ('track_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Track')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
