# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_youtubetrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='processed',
            field=models.DateTimeField(null=True),
        ),
    ]
