# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_track_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistlink',
            name='published',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='playlistlink',
            name='refreshed',
            field=models.DateTimeField(null=True),
        ),
    ]
