# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20170305_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistlink',
            name='random_album_art',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
