version: '2'
services:
  gspotsyncer:
    build: .
    command: /var/gspotsyncer/run_gspotsyncer.sh
    volumes:
      - ./src:/var/gspotsyncer
    env_file:
      - ./docker/environment.env
    depends_on:
      - postgres
      - redis
      - rabbitmq
    links:
      - postgres
      - redis
      - rabbitmq
    restart: always

  worker:
    build: .
    command: /var/gspotsyncer/run_worker.sh
    volumes:
      - ./src:/var/gspotsyncer
    user: worker
    env_file:
      - ./docker/environment.env
    links:
      - postgres
      - redis
      - rabbitmq
    depends_on:
      - rabbitmq

  postgres:
    image: postgres
    env_file:
      - ./docker/environment.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    env_file:
      - ./docker/environment.env

  rabbitmq:
    image: rabbitmq
    env_file:
      - ./docker/environment.env
    ports:
      - "5672:5672"